### ISSUE TITLE
Sane Github is very different from the old design

### ISSUE THREAD

**Issue by Tau5** [MCHSL/sane-github#10]
There are differences from the old design that make the page look some-waht ugly and adds a lot of space

**Old design from the Wayback machine**
![old](https://user-images.githubusercontent.com/28908976/85625203-5ad6bd80-b66b-11ea-8075-559674e07134.png)

**New design with Sane Github**
![sane1](https://user-images.githubusercontent.com/28908976/85625258-75a93200-b66b-11ea-8901-62c7981e3eed.png)
![sane2](https://user-images.githubusercontent.com/28908976/85625264-7772f580-b66b-11ea-8dc0-252039b44d5b.png)

**Comment by MCHSL** [comment]
Unfortunately there's only so much one can do with CSS... As this progresses I'll try to make it look as close to the old design as possible.
