### ISSUE TITLE
PR files changed is fukked

### ISSUE THREAD

**Issue by ZeWaka** [MCHSL/sane-github#2]
![image](https://user-images.githubusercontent.com/4741640/85482694-45349b80-b578-11ea-9046-99b7402cd0e4.png)
https://github.com/goonstation/goonstation/pull/1197/files

**Comment by MCHSL** [comment]
works on my machine

edit: nvm I see the issue

**Comment by ZeWaka** [comment]
This'll need some kind of way of figuring out if you're in unified or split mode, since my fix above works for unified, but undoes the current good css for split.
